### ISSUE TITLE
Macos操作系统安装sdk报错

### ISSUE THREAD

**Issue by sjkcdpc** [volcengine/volcengine-python-sdk#1]
Macos操作系统安装sdk报错
- 系统版本：10.15.7 (19H2026)

# pip install volcengine-python-sdk
Collecting volcengine-python-sdk
  Downloading volcengine-python-sdk-1.0.38.tar.gz (932 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 932.1/932.1 kB 759.5 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      /usr/local/Cellar/python@3.8/3.8.13_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
        warnings.warn(msg)
      /usr/local/Cellar/python@3.8/3.8.13_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'include_package_data'
        warnings.warn(msg)
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
      
      error: invalid command 'egg_info'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by zpp12354321** [comment]
hi @sjkcdpc 

It looks like your environment is missing setuptools somehow.

please try

1. pip install --upgrade pip

2. pip install --upgrade setuptools
