### ISSUE TITLE
个人用户使用 API 服务

### ISSUE THREAD

**Issue by RexWzh** [volcengine/volcengine-python-sdk#3]
你好，请问模型 API 仅对企业开发吗？

API 文档：https://www.volcengine.com/docs/82379/1263279

> **注意**
> 1. API key 具有使用时限，过期后请重新获取；
> 2. 需要先获取推理接入点（Endpoint）的读权限才能使用您的AK SK 换取API key。

控制台限制了仅企业认证可访问：https://console.volcengine.com/ark

<img width="492" alt="image" src="https://github.com/volcengine/volcengine-python-sdk/assets/62223937/dd7f3b51-411e-463e-9ee0-0882781cfb03">

**Comment by daydayup2024** [comment]
是的，咨询过了
![image](https://github.com/volcengine/volcengine-python-sdk/assets/164139977/34ad2a60-fe89-4120-b4c3-6a46a81709b2)
